### ISSUE TITLE
能不能把这个工具集成到Excel VBA编辑器里

### ISSUE THREAD

**Issue by tsiank** [cdhigh/tkinter-designer#12]
现在VB6很少有电脑安装的，但是Excel基本上每台电脑都会安装，里面也有VB编程环境（VBA），如果可以和Excel集成，那就再方便不过了。

**Comment by cdhigh** [comment]
VBA对窗体的操控欠缺一些能力，
而且VB6 SP6精简版才12M, 很小，如果需要，这点空间可以忽略不计，即使针对SSD，更不要说机械硬盘了。

**Comment by tsiank** [comment]
> VBA对窗体的操控欠缺一些能力，
> 而且VB6 SP6精简版才12M， 很小，相当于一个高清图像的大小，如果需要，这点空间可以忽略不计，即使针对SSD，更不要说机械硬盘了。

VB6 SP6在高分屏上会飘移，不能很好地拖放控件。

**Comment by loquat** [comment]
集成的VBA环境，改造起来应该也不难，但是工作量也不小。
