### ISSUE TITLE
貌似超过800多行就不能正常生成py文件了是么？

### ISSUE THREAD

**Issue by lizhaofeng221** [cdhigh/tkinter-designer#15]

**Comment by cdhigh** [comment]
有可能，因直接使用VB的TextBox加载生成的代码，而VB对其的限制为32K。
话说你的窗体内容可真多，如果窗体太复杂，一般的工程实践是不建议使用tkinter的。
如果使用外部控件代替TextBox，可以突破此限制。

**Comment by lizhaofeng221** [comment]
原来如此，有啥快速方法 突破此限制不？

**Comment by lizhaofeng221** [comment]
https://sourceforge.net/projects/page/

**Comment by lizhaofeng221** [comment]
这个工具 貌似也还行？

**Comment by cdhigh** [comment]
很多类似的工具，可以尝试，然后选择自己最顺手的

**Comment by cdhigh** [comment]
我刚测试了VB的TEXTBOX的极限，为65k，一个窗体上最多能放255个控件。
升级到1.6.5，如果生成的代码超过65K，则直接弹出对话框保存到文件，这样就规避了此问题。
