### ISSUE TITLE
建议用这样的方法判断py版本

### ISSUE THREAD

**Issue by retsyo** [cdhigh/tkinter-designer#4]
将生成的代码中的
try:
    from tkinter import *
except ImportError:  #Python 2.x
改变为
if sys.version_info.major==2:   #Python 2.x

原因是：我在用Anaconda的py27的时候，from tkinter import *不会不错

抱歉，很久没用VB，否则我就自己改源程序了

**Comment by cdhigh** [comment]
实际上，我要吐槽了，Anaconda的封装者有些自以为是了，封装和增强都可以，但是改变和官方的兼容性就不对了，不过这也是上梁不正下梁歪，都是Guido自己带坏的，怨不得别人：）
Python 3k如果开始不要叫Python，而是类似C++那样的，叫P++什么的，并且文件后缀名也不能用py，要用pyp或ppp什么的，估计现在情况要好的多。
没有人将C++当做C，所以我们也不应该将Python 3k叫做Python。
和Linux各种发行版很多不兼容一样，都是自由的代价吧！

好了，吐槽完了，新版本也更新了。
如果要更好的兼容，sys.version_info.major是不够的，而是要用sys.version_info[0]，这样才能兼容python 2.6和之前的版本，比如一些linux预装的2.6版本（包括老的macbook本本）。
所以修改为sys.version_info[0]。
