### ISSUE TITLE
Win10可以用吗？

### ISSUE THREAD

**Issue by ljzecg** [cdhigh/tkinter-designer#8]
手动注册和安装注册之后，工具那边都没有羽毛。
Win10 64位，VB6.0

**Comment by cdhigh** [comment]
微软号称windows10支持VB6的，应该能用。
如果不出现，可以在菜单“外接程序”|"外接程序管理器"里面打开Tkinterdesigner
还有，注册后，不要删除tkinterdesigner.dll所在目录。

**Comment by psjatqpgf** [comment]
试试 管理员权限 运行VB6
