### ISSUE TITLE
源代码部分文件用vb6打开不了

### ISSUE THREAD

**Issue by gxgjames** [cdhigh/tkinter-designer#9]
源代码用vb6打开不了，比如clsCanvas.cls等，可能是您在线编辑了vb6的代码。请您打包下载工程文件后用vb6测试一下。

**Comment by cdhigh** [comment]
我这里没问题。
如果你打不开，一般是某个控件的版本不一致导致，在对应目录下会有对应的log文件，打开看是哪个控件加载出错，然后修改为对应你机器的版本即可，不知道你机器的版本？可以新建一个工程，使用对应的控件，保存，使用记事本打开对应的源码文件，即可找到控件的版本号。
